### PR TITLE
Remove meetup modal

### PR DESCRIPTION
**Pull request by MatthewStanciu**
Since the zephyr has ended, it’s weird to keep getting that modal about meetups popping up. I commented it out in this PR because i don’t know if you wanted the code gone, but feel free to edit however

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
oops

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/**](https://slack-oauth-starter-test-xy120-8hh9se2c2.hackclub.dev/) |
|:-:|
|<a href="https://slack-oauth-starter-test-xy120-8hh9se2c2.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/P79l1ywNkaHs5o7ozLwFNqJs3WQIy4ZsAJ1LZgXcCUdcAKppklcSb7WmmqN7JqxI-DsJ6Fo1ubgkW_SDA2b5jQ.png">(view full size)</a> |







Commit 14411d4cad7ab9be6fe886da76b825594dd6be7c (https://slack-oauth-starter-test-xy120-8hh9se2c2.hackclub.dev).

**Comment by MatthewStanciu** [comment]
I think I had just commented it out incorrectly. I ended up deleting the modal code entirely

**Comment by sampoder** [comment]
thanks Matthew!!

**Pull request merged**
